name: Wren Creative
favicon: null
layout_spectrum: 0.25436
typography_spectrum: 0.76507
title: Electrical | Project Management | Events
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#f47c3d'
    - '#c6c6c6'
    - '#606060'
  brandStrength: 0.4538752834778279
  lightness: 0.756097953999415
  saturation: 0.12726421537809074
  rhythmicContrast: 0.75
purpose: []
